const $ = s => document.querySelector(s);
const base = window.PORTAL_CONFIG.API_BASE_URL.replace(/\/$/, '');
let products = [], category = '', query = '', selected = null;
const dialog = $('#product-dialog');
const escapeHTML = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path){const r=await fetch(base+path);if(!r.ok)throw new Error('API');return r.json()}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500)}
function render(){let list=products.filter(p=>!category||p.category===category);const sort=$('#sort').value;list.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name,'pt-BR'):sort==='popular'?(a,b)=>b.views-a.views:(a,b)=>b.updated_at.localeCompare(a.updated_at));$('#count').textContent=`${list.length} produto${list.length===1?'':'s'}${query?' para “'+query+'”':''}`;$('#empty').hidden=list.length>0;$('#grid').innerHTML=list.map((p,i)=>`<button class="card" data-product="${escapeHTML(p.code)}" aria-label="Abrir mídias de ${escapeHTML(p.name)}"><div class="card-image">${i<2&&sort==='recent'?'<span class="tag">NOVIDADE · DEMO</span>':''}<img src="${escapeHTML(p.images[0]?.thumbnail||'')}" alt="${escapeHTML(p.name)}" loading="lazy"></div><div class="card-meta"><span class="code">CÓD. ${escapeHTML(p.code)}</span><h3>${escapeHTML(p.name)}</h3><span class="card-category">${escapeHTML(p.category)} · ${escapeHTML(p.line)}</span><div class="card-bottom"><span>▧ ${p.images.length} foto${p.images.length===1?'':'s'}</span><b>Ver mídias ↗</b></div></div></button>`).join('');document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.product));document.querySelectorAll('.card-image img').forEach(img=>img.onerror=()=>{img.hidden=true;const note=document.createElement('span');note.textContent='Imagem indisponível';img.parentElement.append(note)});document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===category))}
let requestId=0;
async function search(){const id=++requestId;$('#error').hidden=true;try{const data=await api('/api/search?q='+encodeURIComponent(query));if(id!==requestId)return;products=data.results;render()}catch{if(id!==requestId)return;$('#grid').innerHTML='';$('#empty').hidden=true;$('#error').hidden=false;$('#count').textContent='Catálogo indisponível'}}
function setCategory(value){category=value;render()}
async function init(){try{const cats=await api('/api/categories');$('#filters').innerHTML=['',...cats].map(c=>`<button class="filter" data-category="${escapeHTML(c)}">${escapeHTML(c||'Todos os produtos')}</button>`).join('');$('#side-categories').innerHTML=cats.map(c=>`<button class="category-side" data-category="${escapeHTML(c)}">${escapeHTML(c)}</button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));await search();const code=new URLSearchParams(location.search).get('produto');if(code)await openProduct(code)}catch{$('#error').hidden=false;$('#count').textContent='Catálogo indisponível'}}
async function openProduct(code){try{selected=await api('/api/products/'+encodeURIComponent(code));$('#product-name').textContent=selected.name;$('#product-category').textContent=selected.category+' / '+selected.line;$('#product-code').textContent='Código '+selected.code;$('#product-description').textContent=selected.description;$('#reference').textContent=selected.reference;$('#ean').textContent=selected.ean;$('#detail-image').src=selected.images[0]?.url||'';$('#detail-image').alt=selected.name;$('#photo-count').textContent=selected.images.length;$('#video-count').textContent=selected.videos.length;showMedia('images');if(!dialog.open)dialog.showModal()}catch{toast('Não foi possível abrir este produto.')}}
function showMedia(type){document.querySelectorAll('[data-media]').forEach(b=>b.classList.toggle('selected',b.dataset.media===type));const files=selected[type];$('#media-content').innerHTML=files.length?files.map(f=>`<div class="file-row"><span>▧ ${escapeHTML(f.file)}</span><a href="${escapeHTML(f.url)}" target="_blank" rel="noopener">Visualizar ↗</a><a href="${escapeHTML(f.url)}" target="_blank" rel="noopener">Abrir para baixar ↗</a></div>`).join(''):'<p class="muted">Nenhum vídeo disponível nesta prévia.</p>';}
$('#search-form').onsubmit=e=>{e.preventDefault();query=$('#search').value.trim();search()};
$('#search').oninput=()=>{clearTimeout(search.timer);search.timer=setTimeout(()=>{query=$('#search').value.trim();search()},250)};
$('#sort').onchange=render;
$('#clear').onclick=()=>{category='';query='';$('#search').value='';search()};$('#retry').onclick=init;
document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{query=b.dataset.query;category='';$('#search').value=query;search()});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n===b));$('#section-title').textContent=b.dataset.view==='latest'?'Novidades':b.dataset.view==='popular'?'Mais acessados · demonstração':'Todos os produtos';$('#sort').value=b.dataset.view==='popular'?'popular':'recent';query='';category='';$('#search').value='';search()});
document.querySelectorAll('[data-media]').forEach(b=>b.onclick=()=>showMedia(b.dataset.media));
$('#close-dialog').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}};
function productURL(){const url=new URL(location.href);url.search='';url.searchParams.set('produto',selected.code);return url.href}
$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(productURL());toast('Link copiado. Na prévia local, ele funciona neste computador.')}catch{toast('Não foi possível copiar o link neste navegador.')}};
$('#whatsapp').onclick=()=>{if(['127.0.0.1','localhost'].includes(location.hostname)){toast('O compartilhamento por WhatsApp ficará disponível após a publicação.');return}window.open('https://wa.me/?text='+encodeURIComponent(selected.name+' — '+productURL()),'_blank','noopener')};
init();
